EMAIL_IS_USED = 'Такий email вже використовується'
PASSWORD_MISMATCH = 'Паролі не співпадають'
INCORRECT_CREDITS = 'Неправильна адреса електронної пошти та/або пароль'
LOGOUT_SUCCESSFUL = 'Logout successful'
LOGIN_SUCCESSFUL = 'Login successful'
