# version: '3.7'
# services:
#   frontend:
#     build:
#       context: .
#     ports:
#     - '8080:8080'
#     volumes:
#     - '.:/app'

# FROM node:lts-alpine

version: '3.7'
services:
  frontend:
    build:
      context: .
    ports:
      - '8080:8080'
    network_mode: "host"
    volumes:
      - '.:/app'
    #   # - '/app/node_modules'