# Generated by Django 4.1 on 2022-09-05 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='category/logo')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('login', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('site', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('owner_name', models.TextField(blank=True, null=True)),
                ('card_number', models.TextField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('month', models.TextField(blank=True, null=True)),
                ('cvv', models.TextField(blank=True, null=True)),
                ('pin_code', models.TextField(blank=True, null=True)),
                ('date_creation', models.TextField(blank=True, null=True)),
                ('date_update', models.TextField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_items.category')),
                ('tag', models.ManyToManyField(blank=True, null=True, to='users_items.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
