# Generated by Django 4.1 on 2022-09-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_items', '0002_alter_tag_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.TextField(),
        ),
    ]
