# Generated by Django 4.1 on 2022-09-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_items', '0003_alter_tag_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='tag',
            field=models.ManyToManyField(blank=True, to='users_items.tag'),
        ),
    ]
