# Generated by Django 4.1 on 2022-09-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_items', '0005_alter_element_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
