# Generated by Django 4.1 on 2022-08-26 08:55

import account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cardeiuser',
            managers=[
                ('objects', account.models.CardeiUserManager()),
            ],
        ),
    ]
