# Generated by Django 4.1 on 2022-09-05 10:50

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_cardeiuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cardeiuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
